### ISSUE TITLE
Users can rely on a stable Clojure/Java/HTTP API

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#383]
* [x] HTTP API needs to be consistent with the Clojure API (endpoints currently have different names)
* [x] 'sync' - deprecate and replace with 'await-tx'?
* [x] We have a number of history functions on the API, some eager, some lazy - let's coalesce around one (probably lazy?)
* [x] Snapshots/tx-log-contexts - should/how should we expose these to users?
* [x] How can we best help users construct topologies?
* [ ] Async Clojure API as first class citizen?
* [x] Card in for removing the Clojure -> Java -> Clojure dance
* [x] Card in for removing the legacy Java API
* [x] Validate remote Java API client for the new API
* [ ] Should we expose `#crux/id` at all?

**Comment by refset** [comment]
I think we can close this one now :slightly_smiling_face:
