### ISSUE TITLE
Users can deploy XTDB into a production infrastructure

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#385]
Additional thoughts from 2019-12-12 catchup:

* Managed AMI (pricing?)
* [ ] A 'deploying XTDB to production' set of docs
* [ ] XTDB load balancing? likely just needs to be documented
* [ ] Document up the various methods we'd recommend to create a Kafka cluster
