### ISSUE TITLE
We have repeatable Crux benchmarks that we can compare against other databases and previous versions of Crux

### ISSUE THREAD

**Issue by jarohen** [xtdb/xtdb#389]
Aims:
* If there's a performance regression, we want to know about it
* We want to be able to use benchmarks in marketing
* When releases make Crux significantly faster, we want to be able to promote it

In scope:
* [x] Evaluate + document what we already have
* [x] Overnight/on-demand run on ECS of various benchmarks (ts-devices, ts-weather, watdiv)
* [x] Metrics visible on a dashboard
* [x] Breakdown of individual watdiv timings (comparative)
* [x] Ingestion timings for comparison DBs
* [x] Index sizes - note that actual disk space used by Crux is extremely obfuscated by Rocks, but I've found that closing and reopening the db reliably triggers compaction (though I'm not sure if that's "partial" or "full")
